# Generated by Django 3.2.8 on 2021-12-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
