# Generated by Django 3.2.8 on 2021-12-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_added_category_article_and_set_default_for_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='eng_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
